# Generated by Django 3.0.8 on 2020-08-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandtable',
            options={'managed': True, 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='storetable',
            options={'managed': True, 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
