# Generated by Django 3.0.8 on 2020-08-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200821_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catagorytable',
            options={'managed': True, 'verbose_name': 'Catagory', 'verbose_name_plural': 'Catagories'},
        ),
        migrations.AlterModelOptions(
            name='storetable',
            options={'managed': False, 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
        migrations.RenameField(
            model_name='brandtable',
            old_name='brand_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='brandtable',
            name='catagory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CatagoryTable'),
        ),
    ]
