# Generated by Django 3.0.8 on 2020-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200821_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandtable',
            name='slug',
            field=models.SlugField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='catagorytable',
            name='slug',
            field=models.SlugField(blank=True, max_length=45, null=True),
        ),
    ]
