# Generated by Django 3.0.8 on 2020-08-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200821_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecificationtable',
            options={'managed': False, 'verbose_name': 'Product Specification', 'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.AlterModelOptions(
            name='producttable',
            options={'managed': False, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
