# Generated by Django 3.0.8 on 2020-08-22 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200822_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttable',
            options={'managed': True, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
