# Generated by Django 3.0.8 on 2020-08-22 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200822_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='image',
            field=models.ImageField(default='product_pics/product_default.png', upload_to='product_pics'),
        ),
    ]
