# Generated by Django 3.0.8 on 2020-08-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200822_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttable',
            options={'managed': False, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='storetable',
            options={'managed': True, 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
