# Generated by Django 3.0.8 on 2020-08-22 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200822_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storetable',
            name='slug',
        ),
        migrations.AddField(
            model_name='storetable',
            name='image',
            field=models.ImageField(default='store_pics/product_default.png', upload_to='store_pics'),
        ),
    ]
