# Generated by Django 3.0.8 on 2020-08-22 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200822_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storetable',
            options={'managed': False, 'verbose_name': 'Store', 'verbose_name_plural': 'Stores'},
        ),
    ]
