# Generated by Django 3.0.8 on 2020-08-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='slug',
        ),
    ]
