# Generated by Django 3.0.8 on 2020-08-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_wishlist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=150, null=True),
        ),
    ]
